version: "3.9"

services:

  arangodb:
    image: arangodb:3.5.3
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_PASSWORD}

  janusgraph:
    image: janusgraph/janusgraph:0.5
    ports:
      - "8182:8182"
